yarnPath: .yarn/releases/yarn-4.2.2.cjs
nodeLinker: node-modules
# npm registery
npmRegistryServer: 'https://artifactory.yektanet.tech/artifactory/api/npm/npm/'
npmAuthIdent: 'yektanet:nh8E3mbg9F7qSsBsF7bE'
npmAlwaysAuth: true
